### ISSUE TITLE
Package Stack Implementation

### ISSUE THREAD

**Issue by JacKyDev** [JacKyDev/utils#14]
The development stack for the package should be set up.

**Tasks**

- [ ] A code checker and formatter must be added.
- [ ] Ensure that doc comments are defined to provide further IDE examples and developer support.
- [ ] Vitest must be added.
- [ ] A bundle must be added to generate the output.
- [ ] Add more ADRs if they are still missing
